Show error messages if specific version of application available

diff --git a/lib/morevna-studio/morevna-studio b/lib/morevna-studio/morevna-studio
--- a/lib/morevna-studio/morevna-studio
+++ b/lib/morevna-studio/morevna-studio
@@ -197,11 +197,19 @@ exec()
 	    done
 	fi
 	# 3. Use 0-install
-	if [ ${FOUND} != 1 ] && [ ${USE_0INSTALL} == 1 ]; then
+	if [ ${FOUND} != 1 ] && [ ${USE_0INSTALL} == 1 ] && [ ! -z "${URI_0INSTALL}" ]; then
 	    VERSION_OPTION="--version=${APP_VERSION}"
 	    # We can call alternative binary via "--command" option.
 	    # See - https://docs.0install.net/specifications/feed/#commands
 	    0install run ${VERSION_OPTION} --command=${BINARY_0INSTALL_OPTION} ${URI_0INSTALL} "${@:2}"
+	else
+	    echo "ERROR: Unable to find any installation of '${APP}'."
+	    echo "       Please make sure to add following line to"
+	    echo "       '${MOREVNASTUDIO_DIR}/etc/morevnastudio.d/${APP}.ini':"
+	    echo
+	    echo "              ${APP_NAME_UPPERCASE}_${APP_VERSION}=\"/path/to/app/binary\""
+	    echo
+	    exit 1
 	fi
     else
 	# 1. Read ini configuration
@@ -238,7 +246,7 @@ exec()
 	    done
 	fi
 	# 3. Use 0-install
-	if [ "${FOUND}" != 1 ] && [ "${USE_0INSTALL}" == 1 ]; then
+	if [ "${FOUND}" != 1 ] && [ "${USE_0INSTALL}" == 1 ] && [ ! -z "${URI_0INSTALL}" ]; then
 	    VERSION_OPTION=""
 	    # We can call alternative binary via "--command" option.
 	    # See - https://docs.0install.net/specifications/feed/#commands
@@ -288,8 +296,11 @@ exec()
 		"${LATEST_VERSION_PATH}" "${@:2}"
 	    else
 		echo "ERROR: Unable to find any installation of '${APP}'."
-		echo "       Please make sure to add following line to '${MOREVNASTUDIO_DIR}/etc/morevnastudio.d/${APP}.ini':"
+		echo "       Please make sure to add following line to"
+		echo "       '${MOREVNASTUDIO_DIR}/etc/morevnastudio.d/${APP}.ini':"
+		echo
 		echo "              ${APP_NAME_UPPERCASE}_DEFAULT=\"/path/to/app/binary\""
+		echo
 		exit 1
 	    fi
 	fi
