fix: Fix double-launching issue. Some unification for code logic.

diff --git a/lib/morevna-toolchain/morevna-toolchain b/lib/morevna-toolchain/morevna-toolchain
--- a/lib/morevna-toolchain/morevna-toolchain
+++ b/lib/morevna-toolchain/morevna-toolchain
@@ -161,8 +161,8 @@ exec()
     #  - 0install
     #  - /opt/package-version (latest) (fallback)
     
+    FOUND=0
     if [ ! -z ${APP_VERSION} ]; then
-		FOUND=0
 		# 1. Read ini configuration
 		if [ -f "${MOREVNATOOLCHAIN_DIR}/etc/morevna-toolchain.d/${APP}.ini" ]; then
 			APP_PATH=""
@@ -247,6 +247,7 @@ exec()
 		# 3. Use 0-install
 		if [ "${FOUND}" != 1 ] && [ "${USE_0INSTALL}" == 1 ] && [ ! -z "${URI_0INSTALL}" ]; then
 			VERSION_OPTION=""
+			FOUND=1
 			# We can call alternative binary via "--command" option.
 			# See - https://docs.0install.net/specifications/feed/#commands
 			0install run ${VERSION_OPTION} --command=${BINARY_0INSTALL_OPTION} ${URI_0INSTALL} "${@:2}"
@@ -290,16 +291,18 @@ exec()
 			
 			if [ ! -z "${LATEST_VERSION_PATH}" ]; then
 				echo "${LATEST_VERSION_PATH}"
+				FOUND=1
 				"${LATEST_VERSION_PATH}" "${@:2}"
-			else
-				echo "ERROR: Unable to find any installation of '${APP}'."
-				echo "       Please make sure to add following line to"
-				echo "       '${MOREVNATOOLCHAIN_DIR}/etc/morevna-toolchain.d/${APP}.ini':"
-				echo
-				echo "              ${APP_NAME_UPPERCASE}_DEFAULT=\"/path/to/app/binary\""
-				echo
-				exit 1
 			fi
+		fi
+		if [ "${FOUND}" != 1 ]; then
+			echo "ERROR: Unable to find any installation of '${APP}'."
+			echo "       Please make sure to add following line to"
+			echo "       '${MOREVNATOOLCHAIN_DIR}/etc/morevna-toolchain.d/${APP}.ini':"
+			echo
+			echo "              ${APP_NAME_UPPERCASE}_DEFAULT=\"/path/to/app/binary\""
+			echo
+			exit 1
 		fi
     fi
 }
